version: '3.3'
name: tapd-regtest-network
services:
  backend:
    stop_grace_period: 5m
    image: lightninglabs/bitcoin-core:25
    container_name: bitcoind-backend
    hostname: backend
    command: >-
      /home/bitcoin/start.sh
    volumes:
      - ./volumes/bitcoind/backend:/root/.bitcoin
      - ./config/start.sh:/home/bitcoin/start.sh
      - ./config/setup.sh:/home/bitcoin/setup.sh
      - ./config/mining.sh:/home/bitcoin/mining.sh
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18443:18443'
      - '19444:18444'
      - '28334:28334'
      - '29335:28335'
  alice:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: lightninglabs/lnd:v0.17.0-beta
    container_name: regtest-alice-lnd
    hostname: regtest-alice-lnd
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=alice --externalip=regtest-alice-lnd
      --tlsextradomain=regtest-alice-lnd --tlsextradomain=regtest-alice-lnd
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind-backend --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://bitcoind-backend:28334
      --bitcoind.zmqpubrawtx=tcp://bitcoind-backend:28335
    restart: always
    volumes:
      - ./volumes/lnd/alice:/root/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8081:8080'
      - '10001:10009'
      - '9735:9735'
  # bob:
  #   environment:
  #     USERID: ${USERID:-1000}
  #     GROUPID: ${GROUPID:-1000}
  #   stop_grace_period: 2m
  #   image: polarlightning/lnd:0.17.0-beta
  #   container_name: regtest-bob-lnd
  #   hostname: bob
  #   command: >-
  #     lnd --noseedbackup --trickledelay=5000 --alias=bob --externalip=bob
  #     --tlsextradomain=bob --tlsextradomain=regtest-bob-lnd --listen=0.0.0.0:9735
  #     --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
  #     --bitcoin.regtest --bitcoin.node=bitcoind
  #     --bitcoind.rpchost=bitcoind-backend --bitcoind.rpcuser=polaruser
  #     --bitcoind.rpcpass=polarpass
  #     --bitcoind.zmqpubrawblock=tcp://bitcoind-backend:28334
  #     --bitcoind.zmqpubrawtx=tcp://bitcoind-backend:28335
  #   restart: always
  #   volumes:
  #     - ./volumes/lnd/bob:/root/.lnd
  #   expose:
  #     - '8080'
  #     - '10009'
  #     - '9735'
  #   ports:
  #     - '8082:8080'
  #     - '10002:10009'
  #     - '9736:9735'
  alice-tap:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: lightninglabs/taproot-assets:v0.3.0-alpha.rc2
    container_name: regtest-alice-tap
    hostname: regtest-alice-tap
    command: >-
      tapd --network=regtest --debuglevel=debug --tlsextradomain=regtest-alice-tap
      --tlsextradomain=regtest-alice-tap --rpclisten=0.0.0.0:10029
      --restlisten=0.0.0.0:8089 --lnd.host=regtest-alice-lnd:10009
      --lnd.macaroonpath=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
      --lnd.tlspath=/root/.lnd/tls.cert
    restart: always
    volumes:
      - ./volumes/lnd/alice:/root/.lnd
      - ./volumes/tapd/regtest-alice-tap:/root/.tapd
    expose:
      - '8089'
      - '10029'
    ports:
      - '8289:8089'
      - '12029:10029'
  # regtest-bob-tap:
  #   environment:
  #     USERID: ${USERID:-1000}
  #     GROUPID: ${GROUPID:-1000}
  #   stop_grace_period: 2m
  #   image: polarlightning/tapd:0.2.3-alpha
  #   container_name: regtest-bob-tap
  #   hostname: regtest-bob-tap
  #   command: >-
  #     tapd --network=regtest --debuglevel=debug --tlsextradomain=regtest-bob-tap
  #     --tlsextradomain=regtest-bob-tap --rpclisten=0.0.0.0:10029
  #     --restlisten=0.0.0.0:8089 --lnd.host=regtest-bob-lnd:10009
  #     --lnd.macaroonpath=/home/tap/.lnd/data/chain/bitcoin/regtest/admin.macaroon
  #     --lnd.tlspath=/home/tap/.lnd/tls.cert
  #   restart: always
  #   volumes:
  #     - ./volumes/lnd/bob:/home/tap/.lnd
  #     - ./volumes/tapd/regtest-bob-tap:/home/tap/.tapd
  #   expose:
  #     - '8089'
  #     - '10029'
  #   ports:
  #     - '8290:8089'
  #     - '12030:10029'
